network:
  version: 2
  renderer: NetworkManager
  wifis:
    wlan0:
      dhcp4: true
      access-points:
        "robotic":
          password: "#robotic"
          priority: 10
        "RoboCup":
          password: "#robotic"
          priority: 20
        "ROBU":
          password: "#robotic"
          priority: 30
